### ISSUE TITLE
posebusters v0.3.1 failed release

### ISSUE THREAD

**Issue by peterbygrave** [conda-forge/posebusters-feedstock#9]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

After merging #8, posebusters v0.3.1 failed to release and is not available on conda-forge channel: https://anaconda.org/conda-forge/posebusters/files.

Tried to look if anything I can do to re-run but not. Perhaps we can bump build number?

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by jan-janssen** [comment]
@peterbygrave Thanks for the feedback. I triggered a new build and it is now available on https://anaconda.org/conda-forge/posebusters/files
